### PR TITLE
Code Review: HTML Forms

### PR DESCRIPTION
**Pull request by martin-cervantes**
Project is ready for review

### CODE REVIEW

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi **TEAM**, congratulations, your project looks exactly like the original. 👍  We have great commit messages. 😄  However, there are a few fixes we need to address. Find the comments below:
* Kindly add [stickler file](https://github.com/microverseinc/linters-config/tree/master/css) to your project and enable stickler by visiting [stickler-ci.com](https://stickler-ci.com/)
* Our Pull Request needs to be improved. The description should describe the main idea of the project(project-specific). Kindly edit it in your next submission
* Let us address the intuit logo section. Check images below
logo-txt
Currently, we have only an image representing both image and text. Let us fix it
* We currently have 1 warning message. It is easily fixable, let's fix it
script
* Let us add our emails in the author section of the README

Kindly fix these and submit another code review 😃 
_Happy coding_ 👨‍💻 
Daniel Larbi Addo

**Comment by martin-cervantes1** [comment]
-    Add node_modules and json file to git ignore
 -    Add hover pseudo-selector to the buttons
 -    Check validation of HTML file
 -    Fix problems from strickler linter

**Review by addod19 — APPROVED** [review]
## Status: Approved 🏆 🎈 

Hi **TEAM**, congratulations on implementing all the requested changes by the previous TSE's 👍 
The project looks great, README looks professional. Therefore, your project has been approved 😄 
Go ahead and merge to master and submit the project completion form

Good luck with your next projects 👌 
_Happy coding_ 👨‍💻 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by Teshager21** [comment]
Done!

**Pull request merged**
